//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleCop.CSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TypeNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TypeNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleCop.CSharp.TypeNames", typeof(TypeNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accessor.
        /// </summary>
        internal static string Accessor {
            get {
                return ResourceManager.GetString("Accessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accessors.
        /// </summary>
        internal static string AccessorPlural {
            get {
                return ResourceManager.GetString("AccessorPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anonymous method expression.
        /// </summary>
        internal static string AnonymousMethodExpression {
            get {
                return ResourceManager.GetString("AnonymousMethodExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anonymous method expressions.
        /// </summary>
        internal static string AnonymousMethodExpressionPlural {
            get {
                return ResourceManager.GetString("AnonymousMethodExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arithmetic expression.
        /// </summary>
        internal static string ArithmeticExpression {
            get {
                return ResourceManager.GetString("ArithmeticExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arithmetic expressions.
        /// </summary>
        internal static string ArithmeticExpressionPlural {
            get {
                return ResourceManager.GetString("ArithmeticExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to array access expression.
        /// </summary>
        internal static string ArrayAccessExpression {
            get {
                return ResourceManager.GetString("ArrayAccessExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to array access expressions.
        /// </summary>
        internal static string ArrayAccessExpressionPlural {
            get {
                return ResourceManager.GetString("ArrayAccessExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to array initializer expression.
        /// </summary>
        internal static string ArrayInitializerExpression {
            get {
                return ResourceManager.GetString("ArrayInitializerExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to array initializer expressions.
        /// </summary>
        internal static string ArrayInitializerExpressionPlural {
            get {
                return ResourceManager.GetString("ArrayInitializerExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as expression.
        /// </summary>
        internal static string AsExpression {
            get {
                return ResourceManager.GetString("AsExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as expressions.
        /// </summary>
        internal static string AsExpressionPlural {
            get {
                return ResourceManager.GetString("AsExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assembly or module attribute.
        /// </summary>
        internal static string AssemblyOrModuleAttribute {
            get {
                return ResourceManager.GetString("AssemblyOrModuleAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assembly or module attributes.
        /// </summary>
        internal static string AssemblyOrModuleAttributePlural {
            get {
                return ResourceManager.GetString("AssemblyOrModuleAttributePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assignment expression.
        /// </summary>
        internal static string AssignmentExpression {
            get {
                return ResourceManager.GetString("AssignmentExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assignment expressions.
        /// </summary>
        internal static string AssignmentExpressionPlural {
            get {
                return ResourceManager.GetString("AssignmentExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute expression.
        /// </summary>
        internal static string AttributeExpression {
            get {
                return ResourceManager.GetString("AttributeExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute expressions.
        /// </summary>
        internal static string AttributeExpressionPlural {
            get {
                return ResourceManager.GetString("AttributeExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to block statement.
        /// </summary>
        internal static string BlockStatement {
            get {
                return ResourceManager.GetString("BlockStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to block statements.
        /// </summary>
        internal static string BlockStatementPlural {
            get {
                return ResourceManager.GetString("BlockStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to break statement.
        /// </summary>
        internal static string BreakStatement {
            get {
                return ResourceManager.GetString("BreakStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to break statements.
        /// </summary>
        internal static string BreakStatementPlural {
            get {
                return ResourceManager.GetString("BreakStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cast expression.
        /// </summary>
        internal static string CastExpression {
            get {
                return ResourceManager.GetString("CastExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cast expressions.
        /// </summary>
        internal static string CastExpressionPlural {
            get {
                return ResourceManager.GetString("CastExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to catch statement.
        /// </summary>
        internal static string CatchStatement {
            get {
                return ResourceManager.GetString("CatchStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to catch statements.
        /// </summary>
        internal static string CatchStatementPlural {
            get {
                return ResourceManager.GetString("CatchStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checked expression.
        /// </summary>
        internal static string CheckedExpression {
            get {
                return ResourceManager.GetString("CheckedExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checked expressions.
        /// </summary>
        internal static string CheckedExpressionPlural {
            get {
                return ResourceManager.GetString("CheckedExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checked statement.
        /// </summary>
        internal static string CheckedStatement {
            get {
                return ResourceManager.GetString("CheckedStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checked statements.
        /// </summary>
        internal static string CheckedStatementPlural {
            get {
                return ResourceManager.GetString("CheckedStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class.
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to classes.
        /// </summary>
        internal static string ClassPlural {
            get {
                return ResourceManager.GetString("ClassPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collection initializer expression.
        /// </summary>
        internal static string CollectionInitializerExpression {
            get {
                return ResourceManager.GetString("CollectionInitializerExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collection initializer expressions.
        /// </summary>
        internal static string CollectionInitializerExpressionPlural {
            get {
                return ResourceManager.GetString("CollectionInitializerExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conditional expression.
        /// </summary>
        internal static string ConditionalExpression {
            get {
                return ResourceManager.GetString("ConditionalExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conditional expressions.
        /// </summary>
        internal static string ConditionalExpressionPlural {
            get {
                return ResourceManager.GetString("ConditionalExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conditional-logical expression.
        /// </summary>
        internal static string ConditionalLogicalExpression {
            get {
                return ResourceManager.GetString("ConditionalLogicalExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conditional-logical expressions.
        /// </summary>
        internal static string ConditionalLogicalExpressionPlural {
            get {
                return ResourceManager.GetString("ConditionalLogicalExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to constructor.
        /// </summary>
        internal static string Constructor {
            get {
                return ResourceManager.GetString("Constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to constructor initializer.
        /// </summary>
        internal static string ConstructorInitializerStatement {
            get {
                return ResourceManager.GetString("ConstructorInitializerStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to constructor initializers.
        /// </summary>
        internal static string ConstructorInitializerStatementPlural {
            get {
                return ResourceManager.GetString("ConstructorInitializerStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to constructors.
        /// </summary>
        internal static string ConstructorPlural {
            get {
                return ResourceManager.GetString("ConstructorPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue statement.
        /// </summary>
        internal static string ContinueStatement {
            get {
                return ResourceManager.GetString("ContinueStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue statements.
        /// </summary>
        internal static string ContinueStatementPlural {
            get {
                return ResourceManager.GetString("ContinueStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decrement expression.
        /// </summary>
        internal static string DecrementExpression {
            get {
                return ResourceManager.GetString("DecrementExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decrement expressions.
        /// </summary>
        internal static string DecrementExpressionPlural {
            get {
                return ResourceManager.GetString("DecrementExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default value expression.
        /// </summary>
        internal static string DefaultValueExpression {
            get {
                return ResourceManager.GetString("DefaultValueExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default value expressions.
        /// </summary>
        internal static string DefaultValueExpressionPlural {
            get {
                return ResourceManager.GetString("DefaultValueExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delegate.
        /// </summary>
        internal static string Delegate {
            get {
                return ResourceManager.GetString("Delegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delegates.
        /// </summary>
        internal static string DelegatePlural {
            get {
                return ResourceManager.GetString("DelegatePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to destructor.
        /// </summary>
        internal static string Destructor {
            get {
                return ResourceManager.GetString("Destructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to destructors.
        /// </summary>
        internal static string DestructorPlural {
            get {
                return ResourceManager.GetString("DestructorPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document root.
        /// </summary>
        internal static string DocumentRoot {
            get {
                return ResourceManager.GetString("DocumentRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document roots.
        /// </summary>
        internal static string DocumentRootPlural {
            get {
                return ResourceManager.GetString("DocumentRootPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do-while statement.
        /// </summary>
        internal static string DoWhileStatement {
            get {
                return ResourceManager.GetString("DoWhileStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do-while statements.
        /// </summary>
        internal static string DoWhileStatementPlural {
            get {
                return ResourceManager.GetString("DoWhileStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to else statement.
        /// </summary>
        internal static string ElseStatement {
            get {
                return ResourceManager.GetString("ElseStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to else statements.
        /// </summary>
        internal static string ElseStatementPlural {
            get {
                return ResourceManager.GetString("ElseStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty element.
        /// </summary>
        internal static string EmptyElement {
            get {
                return ResourceManager.GetString("EmptyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty elements.
        /// </summary>
        internal static string EmptyElementPlural {
            get {
                return ResourceManager.GetString("EmptyElementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty statement (extra semicolon).
        /// </summary>
        internal static string EmptyStatement {
            get {
                return ResourceManager.GetString("EmptyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty statements (extra semicolons).
        /// </summary>
        internal static string EmptyStatementPlural {
            get {
                return ResourceManager.GetString("EmptyStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enum.
        /// </summary>
        internal static string Enum {
            get {
                return ResourceManager.GetString("Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enum item.
        /// </summary>
        internal static string EnumItem {
            get {
                return ResourceManager.GetString("EnumItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enum items.
        /// </summary>
        internal static string EnumItemPlural {
            get {
                return ResourceManager.GetString("EnumItemPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enums.
        /// </summary>
        internal static string EnumPlural {
            get {
                return ResourceManager.GetString("EnumPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events.
        /// </summary>
        internal static string EventPlural {
            get {
                return ResourceManager.GetString("EventPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expression statement.
        /// </summary>
        internal static string ExpressionStatement {
            get {
                return ResourceManager.GetString("ExpressionStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expression statements.
        /// </summary>
        internal static string ExpressionStatementPlural {
            get {
                return ResourceManager.GetString("ExpressionStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extern alias directive.
        /// </summary>
        internal static string ExternAliasDirective {
            get {
                return ResourceManager.GetString("ExternAliasDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extern alias directives.
        /// </summary>
        internal static string ExternAliasDirectivePlural {
            get {
                return ResourceManager.GetString("ExternAliasDirectivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field.
        /// </summary>
        internal static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fields.
        /// </summary>
        internal static string FieldPlural {
            get {
                return ResourceManager.GetString("FieldPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finally statement.
        /// </summary>
        internal static string FinallyStatement {
            get {
                return ResourceManager.GetString("FinallyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finally statements.
        /// </summary>
        internal static string FinallyStatementPlural {
            get {
                return ResourceManager.GetString("FinallyStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fixed statement.
        /// </summary>
        internal static string FixedStatement {
            get {
                return ResourceManager.GetString("FixedStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fixed statements.
        /// </summary>
        internal static string FixedStatementPlural {
            get {
                return ResourceManager.GetString("FixedStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to foreach statement.
        /// </summary>
        internal static string ForeachStatement {
            get {
                return ResourceManager.GetString("ForeachStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to foreach statements.
        /// </summary>
        internal static string ForeachStatementPlural {
            get {
                return ResourceManager.GetString("ForeachStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for statement.
        /// </summary>
        internal static string ForStatement {
            get {
                return ResourceManager.GetString("ForStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for statements.
        /// </summary>
        internal static string ForStatementPlural {
            get {
                return ResourceManager.GetString("ForStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to goto statement.
        /// </summary>
        internal static string GotoStatement {
            get {
                return ResourceManager.GetString("GotoStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to goto statements.
        /// </summary>
        internal static string GotoStatementPlural {
            get {
                return ResourceManager.GetString("GotoStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if statement.
        /// </summary>
        internal static string IfStatement {
            get {
                return ResourceManager.GetString("IfStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if statements.
        /// </summary>
        internal static string IfStatementPlural {
            get {
                return ResourceManager.GetString("IfStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to increment expression.
        /// </summary>
        internal static string IncrementExpression {
            get {
                return ResourceManager.GetString("IncrementExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to increment expressions.
        /// </summary>
        internal static string IncrementExpressionPlural {
            get {
                return ResourceManager.GetString("IncrementExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indexer.
        /// </summary>
        internal static string Indexer {
            get {
                return ResourceManager.GetString("Indexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indexers.
        /// </summary>
        internal static string IndexerPlural {
            get {
                return ResourceManager.GetString("IndexerPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interface.
        /// </summary>
        internal static string Interface {
            get {
                return ResourceManager.GetString("Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interfaces.
        /// </summary>
        internal static string InterfacePlural {
            get {
                return ResourceManager.GetString("InterfacePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is expression.
        /// </summary>
        internal static string IsExpression {
            get {
                return ResourceManager.GetString("IsExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is expressions.
        /// </summary>
        internal static string IsExpressionPlural {
            get {
                return ResourceManager.GetString("IsExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label statement.
        /// </summary>
        internal static string LabelStatement {
            get {
                return ResourceManager.GetString("LabelStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label statements.
        /// </summary>
        internal static string LabelStatementPlural {
            get {
                return ResourceManager.GetString("LabelStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lambda expression.
        /// </summary>
        internal static string LambdaExpression {
            get {
                return ResourceManager.GetString("LambdaExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lambda expressions.
        /// </summary>
        internal static string LambdaExpressionPlural {
            get {
                return ResourceManager.GetString("LambdaExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to literal expression.
        /// </summary>
        internal static string LiteralExpression {
            get {
                return ResourceManager.GetString("LiteralExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to literal expressions.
        /// </summary>
        internal static string LiteralExpressionPlural {
            get {
                return ResourceManager.GetString("LiteralExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lock statement.
        /// </summary>
        internal static string LockStatement {
            get {
                return ResourceManager.GetString("LockStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lock statements.
        /// </summary>
        internal static string LockStatementPlural {
            get {
                return ResourceManager.GetString("LockStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logical expression.
        /// </summary>
        internal static string LogicalExpression {
            get {
                return ResourceManager.GetString("LogicalExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logical expressions.
        /// </summary>
        internal static string LogicalExpressionPlural {
            get {
                return ResourceManager.GetString("LogicalExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to member access expression.
        /// </summary>
        internal static string MemberAccessExpression {
            get {
                return ResourceManager.GetString("MemberAccessExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to member access expressions.
        /// </summary>
        internal static string MemberAccessExpressionPlural {
            get {
                return ResourceManager.GetString("MemberAccessExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to method.
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to method invocation expression.
        /// </summary>
        internal static string MethodInvocationExpression {
            get {
                return ResourceManager.GetString("MethodInvocationExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to method invocation expressions.
        /// </summary>
        internal static string MethodInvocationExpressionPlural {
            get {
                return ResourceManager.GetString("MethodInvocationExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to methods.
        /// </summary>
        internal static string MethodPlural {
            get {
                return ResourceManager.GetString("MethodPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace.
        /// </summary>
        internal static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespaces.
        /// </summary>
        internal static string NamespacePlural {
            get {
                return ResourceManager.GetString("NamespacePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new array expression.
        /// </summary>
        internal static string NewArrayExpression {
            get {
                return ResourceManager.GetString("NewArrayExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new array expressions.
        /// </summary>
        internal static string NewArrayExpressionPlural {
            get {
                return ResourceManager.GetString("NewArrayExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new expression.
        /// </summary>
        internal static string NewExpression {
            get {
                return ResourceManager.GetString("NewExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new expressions.
        /// </summary>
        internal static string NewExpressionPlural {
            get {
                return ResourceManager.GetString("NewExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null-coalescing expression.
        /// </summary>
        internal static string NullCoalescingExpression {
            get {
                return ResourceManager.GetString("NullCoalescingExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null-coalescing expressions.
        /// </summary>
        internal static string NullCoalescingExpressionPlural {
            get {
                return ResourceManager.GetString("NullCoalescingExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object initializer expression.
        /// </summary>
        internal static string ObjectInitializerExpression {
            get {
                return ResourceManager.GetString("ObjectInitializerExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object initializer expressions.
        /// </summary>
        internal static string ObjectInitializerExpressionPlural {
            get {
                return ResourceManager.GetString("ObjectInitializerExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parenthesized expression.
        /// </summary>
        internal static string ParenthesizedExpression {
            get {
                return ResourceManager.GetString("ParenthesizedExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parenthesized expressions.
        /// </summary>
        internal static string ParenthesizedExpressionPlural {
            get {
                return ResourceManager.GetString("ParenthesizedExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to property.
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to properties.
        /// </summary>
        internal static string PropertyPlural {
            get {
                return ResourceManager.GetString("PropertyPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to into clause.
        /// </summary>
        internal static string QueryContinuationClause {
            get {
                return ResourceManager.GetString("QueryContinuationClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to into clauses.
        /// </summary>
        internal static string QueryContinuationClausePlural {
            get {
                return ResourceManager.GetString("QueryContinuationClausePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query expression.
        /// </summary>
        internal static string QueryExpression {
            get {
                return ResourceManager.GetString("QueryExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query expressions.
        /// </summary>
        internal static string QueryExpressionPlural {
            get {
                return ResourceManager.GetString("QueryExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from clause.
        /// </summary>
        internal static string QueryFromClause {
            get {
                return ResourceManager.GetString("QueryFromClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from clauses.
        /// </summary>
        internal static string QueryFromClausePlural {
            get {
                return ResourceManager.GetString("QueryFromClausePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group clause.
        /// </summary>
        internal static string QueryGroupClause {
            get {
                return ResourceManager.GetString("QueryGroupClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group clauses.
        /// </summary>
        internal static string QueryGroupClausePlural {
            get {
                return ResourceManager.GetString("QueryGroupClausePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to join clause.
        /// </summary>
        internal static string QueryJoinClause {
            get {
                return ResourceManager.GetString("QueryJoinClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to join clauses.
        /// </summary>
        internal static string QueryJoinClausePlural {
            get {
                return ResourceManager.GetString("QueryJoinClausePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to let clause.
        /// </summary>
        internal static string QueryLetClause {
            get {
                return ResourceManager.GetString("QueryLetClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to let clauses.
        /// </summary>
        internal static string QueryLetClausePlural {
            get {
                return ResourceManager.GetString("QueryLetClausePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order-by clause.
        /// </summary>
        internal static string QueryOrderByClause {
            get {
                return ResourceManager.GetString("QueryOrderByClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order-by clauses.
        /// </summary>
        internal static string QueryOrderByClausePlural {
            get {
                return ResourceManager.GetString("QueryOrderByClausePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select clause.
        /// </summary>
        internal static string QuerySelectClause {
            get {
                return ResourceManager.GetString("QuerySelectClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select clauses.
        /// </summary>
        internal static string QuerySelectClausePlural {
            get {
                return ResourceManager.GetString("QuerySelectClausePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to where clause.
        /// </summary>
        internal static string QueryWhereClause {
            get {
                return ResourceManager.GetString("QueryWhereClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to where clauses.
        /// </summary>
        internal static string QueryWhereClausePlural {
            get {
                return ResourceManager.GetString("QueryWhereClausePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relational expression.
        /// </summary>
        internal static string RelationalExpression {
            get {
                return ResourceManager.GetString("RelationalExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relational expressions.
        /// </summary>
        internal static string RelationalExpressionPlural {
            get {
                return ResourceManager.GetString("RelationalExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return statement.
        /// </summary>
        internal static string ReturnStatement {
            get {
                return ResourceManager.GetString("ReturnStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return statements.
        /// </summary>
        internal static string ReturnStatementPlural {
            get {
                return ResourceManager.GetString("ReturnStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sizeof expression.
        /// </summary>
        internal static string SizeofExpression {
            get {
                return ResourceManager.GetString("SizeofExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sizeof expressions.
        /// </summary>
        internal static string SizeofExpressionPlural {
            get {
                return ResourceManager.GetString("SizeofExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stackalloc expression.
        /// </summary>
        internal static string StackallocExpression {
            get {
                return ResourceManager.GetString("StackallocExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stackalloc expressions.
        /// </summary>
        internal static string StackallocExpressionPlural {
            get {
                return ResourceManager.GetString("StackallocExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to struct.
        /// </summary>
        internal static string Struct {
            get {
                return ResourceManager.GetString("Struct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to structs.
        /// </summary>
        internal static string StructPlural {
            get {
                return ResourceManager.GetString("StructPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch-case statement.
        /// </summary>
        internal static string SwitchCaseStatement {
            get {
                return ResourceManager.GetString("SwitchCaseStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch-case statements.
        /// </summary>
        internal static string SwitchCaseStatementPlural {
            get {
                return ResourceManager.GetString("SwitchCaseStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch-default statement.
        /// </summary>
        internal static string SwitchDefaultStatement {
            get {
                return ResourceManager.GetString("SwitchDefaultStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch-default statements.
        /// </summary>
        internal static string SwitchDefaultStatementPlural {
            get {
                return ResourceManager.GetString("SwitchDefaultStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch statement.
        /// </summary>
        internal static string SwitchStatement {
            get {
                return ResourceManager.GetString("SwitchStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch statements.
        /// </summary>
        internal static string SwitchStatementPlural {
            get {
                return ResourceManager.GetString("SwitchStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to throw statement.
        /// </summary>
        internal static string ThrowStatement {
            get {
                return ResourceManager.GetString("ThrowStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to throw statements.
        /// </summary>
        internal static string ThrowStatementPlural {
            get {
                return ResourceManager.GetString("ThrowStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to try statement.
        /// </summary>
        internal static string TryStatement {
            get {
                return ResourceManager.GetString("TryStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to try statements.
        /// </summary>
        internal static string TryStatementPlural {
            get {
                return ResourceManager.GetString("TryStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to typeof expression.
        /// </summary>
        internal static string TypeofExpression {
            get {
                return ResourceManager.GetString("TypeofExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to typeof expressions.
        /// </summary>
        internal static string TypeofExpressionPlural {
            get {
                return ResourceManager.GetString("TypeofExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unary expression.
        /// </summary>
        internal static string UnaryExpression {
            get {
                return ResourceManager.GetString("UnaryExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unary expressions.
        /// </summary>
        internal static string UnaryExpressionPlural {
            get {
                return ResourceManager.GetString("UnaryExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unchecked expression.
        /// </summary>
        internal static string UncheckedExpression {
            get {
                return ResourceManager.GetString("UncheckedExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unchecked expressions.
        /// </summary>
        internal static string UncheckedExpressionPlural {
            get {
                return ResourceManager.GetString("UncheckedExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unchecked statement.
        /// </summary>
        internal static string UncheckedStatement {
            get {
                return ResourceManager.GetString("UncheckedStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unchecked statements.
        /// </summary>
        internal static string UncheckedStatementPlural {
            get {
                return ResourceManager.GetString("UncheckedStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsafe access expression.
        /// </summary>
        internal static string UnsafeAccessExpression {
            get {
                return ResourceManager.GetString("UnsafeAccessExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsafe access expressions.
        /// </summary>
        internal static string UnsafeAccessExpressionPlural {
            get {
                return ResourceManager.GetString("UnsafeAccessExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsafe statement.
        /// </summary>
        internal static string UnsafeStatement {
            get {
                return ResourceManager.GetString("UnsafeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsafe statements.
        /// </summary>
        internal static string UnsafeStatementPlural {
            get {
                return ResourceManager.GetString("UnsafeStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using directive.
        /// </summary>
        internal static string UsingDirective {
            get {
                return ResourceManager.GetString("UsingDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using directives.
        /// </summary>
        internal static string UsingDirectivePlural {
            get {
                return ResourceManager.GetString("UsingDirectivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using statement.
        /// </summary>
        internal static string UsingStatement {
            get {
                return ResourceManager.GetString("UsingStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using statements.
        /// </summary>
        internal static string UsingStatementPlural {
            get {
                return ResourceManager.GetString("UsingStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable declaration expression.
        /// </summary>
        internal static string VariableDeclarationExpression {
            get {
                return ResourceManager.GetString("VariableDeclarationExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable declaration expressions.
        /// </summary>
        internal static string VariableDeclarationExpressionPlural {
            get {
                return ResourceManager.GetString("VariableDeclarationExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable declaration statement.
        /// </summary>
        internal static string VariableDeclarationStatement {
            get {
                return ResourceManager.GetString("VariableDeclarationStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable declaration statements.
        /// </summary>
        internal static string VariableDeclarationStatementPlural {
            get {
                return ResourceManager.GetString("VariableDeclarationStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable declarator expression.
        /// </summary>
        internal static string VariableDeclaratorExpression {
            get {
                return ResourceManager.GetString("VariableDeclaratorExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable declarator expressions.
        /// </summary>
        internal static string VariableDeclaratorExpressionPlural {
            get {
                return ResourceManager.GetString("VariableDeclaratorExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to while statement.
        /// </summary>
        internal static string WhileStatement {
            get {
                return ResourceManager.GetString("WhileStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to while statements.
        /// </summary>
        internal static string WhileStatementPlural {
            get {
                return ResourceManager.GetString("WhileStatementPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yield statement.
        /// </summary>
        internal static string YieldStatement {
            get {
                return ResourceManager.GetString("YieldStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yield statements.
        /// </summary>
        internal static string YieldStatementPlural {
            get {
                return ResourceManager.GetString("YieldStatementPlural", resourceCulture);
            }
        }
    }
}
