#region Whatever generated code

using System;
using System.Collections.Generic;
using System.Text;

namespace AccessModifiersMissing_AutogeneratedRegion.cs
{
    class ClassMissingAccessModifier
    {
    }
}

#endregion
