// <auto-generated />

using System;
using System.Collections.Generic;
using System.Text;

namespace AccessModifiersMissing_AutogeneratedHeader.cs
{
    class ClassMissingAccessModifier
    {
    }
}
