#pragma warning disable 1591
// <auto-generated/>
using System;

// This class contains style violations which should not appear because of the header.
public class Yo
{
    public void Method(int x)
    {
        int x = 0;
    }
}