//-----------------------------------------------------------------------
// <copyright file="FileHeader.cs" company="Microsoft">
//   Copyright (c) Microsoft Corporation.
// </copyright>
// <license>
//   This source code is subject to terms and conditions of the Microsoft 
//   Public License. A copy of the license can be found in the License.html 
//   file at the root of this distribution. If you cannot locate the  
//   Microsoft Public License, please send an email to dlr@microsoft.com. 
//   By using this source code in any fashion, you are agreeing to be bound 
//   by the terms of the Microsoft Public License. You must not remove this 
//   notice, or any other, from this software.
// </license>
//-----------------------------------------------------------------------
namespace Microsoft.StyleCop.CSharp
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Globalization;
    using System.Text;
    using System.Xml;

    /// <summary>
    /// Represents a file header.
    /// </summary>
    public sealed class FileHeader : CodeUnit
    {
        #region Private Fields

        /// <summary>
        /// Indicates whether this is an auto-generated header.
        /// </summary>
        private bool generated;

        #endregion Private Fields

        #region Internal Constructors

        /// <summary>
        /// Initializes a new instance of the FileHeader class.
        /// </summary>
        /// <param name="proxy">Proxy object for the header.</param>
        internal FileHeader(CodeUnitProxy proxy) 
            : base(proxy, CodeUnitType.FileHeader)
        {
            Param.AssertNotNull(proxy, "proxy");

            // Determine whether this is an auto-generated header.
            try
            {
                string headerXml = this.GetHeaderXml();

                if (!string.IsNullOrEmpty(headerXml))
                {
                    var doc = new XmlDocument();
                    doc.LoadXml(string.Format(CultureInfo.InvariantCulture, "<root>{0}</root>", headerXml));

                    // Check whether the header has the autogenerated tag.
                    XmlNode node = doc.DocumentElement["autogenerated"];
                    if (node != null)
                    {
                        // Set this as generated code.
                        this.generated = true;
                    }
                    else
                    {
                        node = doc.DocumentElement["auto-generated"];
                        if (node != null)
                        {
                            // Set this as generated code.
                            this.generated = true;
                        }
                    }
                }
            }
            catch (XmlException)
            {
            }
        }

        #endregion Internal Constructors

        #region Public Override Properties

        /// <summary>
        /// Gets a value indicating whethre the file header is an auto-generated header.
        /// </summary>
        public override bool Generated
        {
            get
            {
                if (this.generated)
                {
                    return true;
                }

                return base.Generated;
            }
        }

        #endregion Public Override Properties

        #region Public Properties

        /// <summary>
        /// Gets the collection of header lines within the header.
        /// </summary>
        public IEnumerable<SingleLineComment> HeaderLines
        {
            get
            {
                return this.GetChildren<SingleLineComment>();
            }
        }

        /// <summary>
        /// Gets a value indicating whether the header contains anything other than whitespace.
        /// </summary>
        public bool IsEmpty
        {
            get
            {
                for (SingleLineComment headerLine = this.FindFirstChild<SingleLineComment>(); headerLine != null; headerLine = headerLine.FindNextSibling<SingleLineComment>())
                {
                    string text = headerLine.Text;
                    if (!string.IsNullOrEmpty(text))
                    {
                        // Start searching at index 2 to move past the initial '//' slashes.
                        for (int i = 3; i < text.Length; ++i)
                        {
                            if (!char.IsWhiteSpace(text[i]))
                            {
                                return false;
                            }
                        }
                    }
                }

                return true;
            }
        }

        #endregion Public Properties

        #region Public Methods

        /// <summary>
        /// Gets the header Xml.
        /// </summary>
        /// <returns>Returns the Xml.</returns>
        public string GetHeaderXml()
        {
            StringBuilder text = new StringBuilder();

            for (XmlHeaderLine headerLine = this.FindFirstChild<XmlHeaderLine>(); headerLine != null; headerLine = headerLine.FindNextSibling<XmlHeaderLine>())
            {
                string headerLineText = headerLine.Text;
                if (headerLineText.StartsWith("//", StringComparison.Ordinal))
                {
                    // Ignore empty lines or lines which start with //-
                    if (headerLineText.Length > 2 && headerLineText[2] != '-')
                    {
                        headerLineText = headerLineText.Substring(2, headerLineText.Length - 2);
                    }
                }

                text.Append(headerLineText);
            }

            return text.ToString();
        }

        /// <summary>
        /// Gets the header Xml with original formatting included.
        /// </summary>
        /// <returns>Returns the formatted Xml.</returns>
        public string GetFormattedHeaderXml()
        {
            StringBuilder text = new StringBuilder();

            for (CodeUnit item = this.FindFirstChild<CodeUnit>(); item != null; item = item.FindNextSibling<CodeUnit>())
            {
                if (item.Is(CommentType.XmlHeaderLine))
                {
                    string headerLineText = ((XmlHeaderLine)item).Text;
                    if (headerLineText.StartsWith("//", StringComparison.Ordinal))
                    {
                        // Ignore empty lines or lines which start with //-
                        if (headerLineText.Length > 2 && headerLineText[2] != '-')
                        {
                            headerLineText = headerLineText.Substring(2, headerLineText.Length - 2);
                        }
                    }

                    text.Append(headerLineText);
                }
                else if (item.Is(LexicalElementType.EndOfLine))
                {
                    text.Append('\n');
                }
            }

            return text.ToString();
        }

        #endregion Public Methods
    }
}
