version = 1

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "angular",
    "vue",
    "ember",
    "meteor",
    "angularjs"
  ]