//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleCop.CSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleCop.CSharp.CodeStrings", typeof(CodeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class.
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizes an instance of the &lt;see cref=&quot;{0}&quot; /&gt; class.
        /// </summary>
        internal static string ExampleHeaderSummaryForDestructor {
            get {
                return ResourceManager.GetString("ExampleHeaderSummaryForDestructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializes a new instance of the &lt;see cref=&quot;{0}&quot; /&gt; {1}.
        /// </summary>
        internal static string ExampleHeaderSummaryForInstanceConstructor {
            get {
                return ResourceManager.GetString("ExampleHeaderSummaryForInstanceConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents a default instance of the &lt;see cref=&quot;{0}&quot; /&gt; {1} from being created.
        /// </summary>
        internal static string ExampleHeaderSummaryForPrivateInstanceConstructor {
            get {
                return ResourceManager.GetString("ExampleHeaderSummaryForPrivateInstanceConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializes static members of the &lt;see cref=&quot;{0}&quot; /&gt; {1}.
        /// </summary>
        internal static string ExampleHeaderSummaryForStaticConstructor {
            get {
                return ResourceManager.GetString("ExampleHeaderSummaryForStaticConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets a value indicating whether.
        /// </summary>
        internal static string HeaderSummaryForBooleanGetAccessor {
            get {
                return ResourceManager.GetString("HeaderSummaryForBooleanGetAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets a value indicating whether.
        /// </summary>
        internal static string HeaderSummaryForBooleanGetAndSetAccessor {
            get {
                return ResourceManager.GetString("HeaderSummaryForBooleanGetAndSetAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets a value indicating whether.
        /// </summary>
        internal static string HeaderSummaryForBooleanSetAccessor {
            get {
                return ResourceManager.GetString("HeaderSummaryForBooleanSetAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizes an instance of the {0} class.
        /// </summary>
        internal static string HeaderSummaryForDestructor {
            get {
                return ResourceManager.GetString("HeaderSummaryForDestructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets.
        /// </summary>
        internal static string HeaderSummaryForGetAccessor {
            get {
                return ResourceManager.GetString("HeaderSummaryForGetAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets.
        /// </summary>
        internal static string HeaderSummaryForGetAndSetAccessor {
            get {
                return ResourceManager.GetString("HeaderSummaryForGetAndSetAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializes a new instance of the {0} {1}.
        /// </summary>
        internal static string HeaderSummaryForInstanceConstructor {
            get {
                return ResourceManager.GetString("HeaderSummaryForInstanceConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents a default instance of the {0} {1} from being created.
        /// </summary>
        internal static string HeaderSummaryForPrivateInstanceConstructor {
            get {
                return ResourceManager.GetString("HeaderSummaryForPrivateInstanceConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets.
        /// </summary>
        internal static string HeaderSummaryForSetAccessor {
            get {
                return ResourceManager.GetString("HeaderSummaryForSetAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializes static members of the {0} {1}.
        /// </summary>
        internal static string HeaderSummaryForStaticConstructor {
            get {
                return ResourceManager.GetString("HeaderSummaryForStaticConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is not used..
        /// </summary>
        internal static string ParameterNotUsed {
            get {
                return ResourceManager.GetString("ParameterNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to struct.
        /// </summary>
        internal static string Struct {
            get {
                return ResourceManager.GetString("Struct", resourceCulture);
            }
        }
    }
}
