//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleCop.CSharp.CodeModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleCop.CSharp.CodeModel.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item to be inserted ({0}) is from a different document content..
        /// </summary>
        internal static string CodeModelDocumentMismatch {
            get {
                return ResourceManager.GetString("CodeModelDocumentMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A code model error has been introduced in document {0}..
        /// </summary>
        internal static string CodeModelError {
            get {
                return ResourceManager.GetString("CodeModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A code model error has been introduce in document {0}: {1}.
        /// </summary>
        internal static string CodeModelErrorWithMessage {
            get {
                return ResourceManager.GetString("CodeModelErrorWithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is of type {1}, but must be one of the following types: {2}.
        /// </summary>
        internal static string CodeModelTypeMismatch {
            get {
                return ResourceManager.GetString("CodeModelTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection is read-only..
        /// </summary>
        internal static string CodeUnitCollectionIsReadOnly {
            get {
                return ResourceManager.GetString("CodeUnitCollectionIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document must be of type CsDocument..
        /// </summary>
        internal static string DocumentMustBeCsDocument {
            get {
                return ResourceManager.GetString("DocumentMustBeCsDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document root.
        /// </summary>
        internal static string DocumentRoot {
            get {
                return ResourceManager.GetString("DocumentRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A element header line must begin with three forward slashes: ///.
        /// </summary>
        internal static string ElementHeaderLineMustBeginWithTripleSlash {
            get {
                return ResourceManager.GetString("ElementHeaderLineMustBeginWithTripleSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element header line must not being with more than three forward slashes in a row..
        /// </summary>
        internal static string ElementHeaderLineMustNotBeginWithQuadrupleSlash {
            get {
                return ResourceManager.GetString("ElementHeaderLineMustNotBeginWithQuadrupleSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element header line must not contain newline characters..
        /// </summary>
        internal static string ElementHeaderLineMustNotContainNewline {
            get {
                return ResourceManager.GetString("ElementHeaderLineMustNotContainNewline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element header line must not contain trailing whitespace..
        /// </summary>
        internal static string ElementHeaderLineMustNotContainsTrailingWhitespace {
            get {
                return ResourceManager.GetString("ElementHeaderLineMustNotContainsTrailingWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element must be in the same document as its parent..
        /// </summary>
        internal static string ElementMustBeInParentsDocument {
            get {
                return ResourceManager.GetString("ElementMustBeInParentsDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty element.
        /// </summary>
        internal static string EmptyElement {
            get {
                return ResourceManager.GetString("EmptyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file header may only contain whitespace, newlines, and single-line comments..
        /// </summary>
        internal static string InvalidFileHeaderElement {
            get {
                return ResourceManager.GetString("InvalidFileHeaderElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of passes..
        /// </summary>
        internal static string InvalidNumberOfPasses {
            get {
                return ResourceManager.GetString("InvalidNumberOfPasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item has already been added to the collection..
        /// </summary>
        internal static string ItemHasAlreadyBeenAddedToCollection {
            get {
                return ResourceManager.GetString("ItemHasAlreadyBeenAddedToCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item has not yet been inserted into a document..
        /// </summary>
        internal static string ItemHasNotBeenAddedToACollection {
            get {
                return ResourceManager.GetString("ItemHasNotBeenAddedToACollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LiteralExpression must contain a TypeToken..
        /// </summary>
        internal static string LiteralExpressionDoesNotContainTypeToken {
            get {
                return ResourceManager.GetString("LiteralExpressionDoesNotContainTypeToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text within a LiteralToken must not consist solely of whitespace characters..
        /// </summary>
        internal static string LiteralMustContainNonWhitespace {
            get {
                return ResourceManager.GetString("LiteralMustContainNonWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A multi-line comment must begin with /* and end with */.
        /// </summary>
        internal static string MultilineCommentMustBeginAndEndWithCommentSyntax {
            get {
                return ResourceManager.GetString("MultilineCommentMustBeginAndEndWithCommentSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A multi-line comment must contain text..
        /// </summary>
        internal static string MultilineCommentMustContainText {
            get {
                return ResourceManager.GetString("MultilineCommentMustContainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find a matching #endregion directive for the #region..
        /// </summary>
        internal static string NoMatchingEndregion {
            get {
                return ResourceManager.GetString("NoMatchingEndregion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find a matching #region directive for the #endregion..
        /// </summary>
        internal static string NoMatchingRegion {
            get {
                return ResourceManager.GetString("NoMatchingRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AssignmentExpression must be of type Equals. Use the CreateEqualsExpression method to create an AssignmentExpression of the appropriate type..
        /// </summary>
        internal static string ObjectInitializerAssignmentIsNotEquals {
            get {
                return ResourceManager.GetString("ObjectInitializerAssignmentIsNotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression on the left-hand side of an AssignmentExpression with an ObjectInitializerExpression must be of type LiteralExpression..
        /// </summary>
        internal static string ObjectInitializerAssignmentLeftHandSideMustBeLiteral {
            get {
                return ResourceManager.GetString("ObjectInitializerAssignmentLeftHandSideMustBeLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter Root property must be null or set to the current CodeUnit node..
        /// </summary>
        internal static string RootInvalid {
            get {
                return ResourceManager.GetString("RootInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A single-line comment must begin with two forward slashes: //.
        /// </summary>
        internal static string SingleLineCommentMustBeginWithDoubleSlash {
            get {
                return ResourceManager.GetString("SingleLineCommentMustBeginWithDoubleSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A single-line comment must not contain newline characters..
        /// </summary>
        internal static string SingleLineCommentMustNotContainNewline {
            get {
                return ResourceManager.GetString("SingleLineCommentMustNotContainNewline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A single-line comment must not contain trailing whitespace..
        /// </summary>
        internal static string SingleLineCommentMustNotContainsTrailingWhitespace {
            get {
                return ResourceManager.GetString("SingleLineCommentMustNotContainsTrailingWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A syntax error has been discovered in document {0} on line {1}..
        /// </summary>
        internal static string SyntaxErrorInFile {
            get {
                return ResourceManager.GetString("SyntaxErrorInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A syntax error has been discovered in document {0} on line {1}: {2}.
        /// </summary>
        internal static string SyntaxErrorInFileWithMessage {
            get {
                return ResourceManager.GetString("SyntaxErrorInFileWithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An assert occured: {0}.
        /// </summary>
        internal static string ThrowOnAssert {
            get {
                return ResourceManager.GetString("ThrowOnAssert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The triple-slash comment style is reserved for documentation header lines..
        /// </summary>
        internal static string TripleSlashIsReservedForDocumentHeaders {
            get {
                return ResourceManager.GetString("TripleSlashIsReservedForDocumentHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file encountered..
        /// </summary>
        internal static string UnexpectedEndOfFile {
            get {
                return ResourceManager.GetString("UnexpectedEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a number..
        /// </summary>
        internal static string ValueMustBeANumber {
            get {
                return ResourceManager.GetString("ValueMustBeANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a string..
        /// </summary>
        internal static string ValueMustBeAString {
            get {
                return ResourceManager.GetString("ValueMustBeAString", resourceCulture);
            }
        }
    }
}
