//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleCop.CSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleCop.CSharp.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to access modifier.
        /// </summary>
        internal static string AccessModifier {
            get {
                return ResourceManager.GetString("AccessModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to closing.
        /// </summary>
        internal static string Closing {
            get {
                return ResourceManager.GetString("Closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Information.
        /// </summary>
        internal static string CompanyInformationTab {
            get {
                return ResourceManager.GetString("CompanyInformationTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The curly brackets within the file do not match..
        /// </summary>
        internal static string CurlyBracketsInFileDoNotMatch {
            get {
                return ResourceManager.GetString("CurlyBracketsInFileDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a one or two digit prefix before clicking the Add button.
        /// </summary>
        internal static string EnterValidPrefix {
            get {
                return ResourceManager.GetString("EnterValidPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        internal static string HungarianTab {
            get {
                return ResourceManager.GetString("HungarianTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company name and copyright boxes must be filled in..
        /// </summary>
        internal static string MissingCompanyOrCopyright {
            get {
                return ResourceManager.GetString("MissingCompanyOrCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opening.
        /// </summary>
        internal static string Opening {
            get {
                return ResourceManager.GetString("Opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Preferred alternate: &apos;{0}&apos;).
        /// </summary>
        internal static string SpellingPreferredAlternate {
            get {
                return ResourceManager.GetString("SpellingPreferredAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Use compound word &apos;{0}&apos;).
        /// </summary>
        internal static string SpellingUseCompoundWord {
            get {
                return ResourceManager.GetString("SpellingUseCompoundWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to static.
        /// </summary>
        internal static string Static {
            get {
                return ResourceManager.GetString("Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleCop.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
