//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleCop.VisualStudio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleCop.VisualStudio.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; has been changed and it needs to be saved, but the file is marked as read-only on the disc. Please make the file writable and try again..
        /// </summary>
        internal static string AccessDeniedWhileSaving {
            get {
                return ResourceManager.GetString("AccessDeniedWhileSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while trying to read the path to the project file from the project system. Please report this error to Microsoft..
        /// </summary>
        internal static string AccessingProjectPropertyThrewException {
            get {
                return ResourceManager.GetString("AccessingProjectPropertyThrewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Integration.
        /// </summary>
        internal static string BuildIntegrationTabTitle {
            get {
                return ResourceManager.GetString("BuildIntegrationTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleCop cancelled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get the path to the project..
        /// </summary>
        internal static string CantGetProjectPath {
            get {
                return ResourceManager.GetString("CantGetProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleCop could not get the Visual Studio environment service..
        /// </summary>
        internal static string CouldNotGetVSEnvironment {
            get {
                return ResourceManager.GetString("CouldNotGetVSEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not navigate to the file..
        /// </summary>
        internal static string CouldNotNavigateToFile {
            get {
                return ResourceManager.GetString("CouldNotNavigateToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} could not be saved. Cancelling StyleCop..
        /// </summary>
        internal static string CouldNotSaveDocument {
            get {
                return ResourceManager.GetString("CouldNotSaveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleCop completed.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found an empty child node &apos;{0}&apos;..
        /// </summary>
        internal static string EmptyChildNode {
            get {
                return ResourceManager.GetString("EmptyChildNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Error Help is available for this StyleCop violation. This is usually the case when a violation is discovered through a custom rule..
        /// </summary>
        internal static string ErrorHelpNotAvailable {
            get {
                return ResourceManager.GetString("ErrorHelpNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving documents..
        /// </summary>
        internal static string ErrorWhileSavingDocument {
            get {
                return ResourceManager.GetString("ErrorWhileSavingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to display the StyleCop rule help documentation..
        /// </summary>
        internal static string FailedToLaunchRulesHelp {
            get {
                return ResourceManager.GetString("FailedToLaunchRulesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; does not exist on the disk..
        /// </summary>
        internal static string FileNotFoundWhileSaving {
            get {
                return ResourceManager.GetString("FileNotFoundWhileSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///---------------------- {0} ----------------------
        ///.
        /// </summary>
        internal static string LogBreak {
            get {
                return ResourceManager.GetString("LogBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VsProjectTypes node is malformed. {0}.
        /// </summary>
        internal static string MalFormedVsProjectLocationNode {
            get {
                return ResourceManager.GetString("MalFormedVsProjectLocationNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///------ {0} ------
        ///.
        /// </summary>
        internal static string MiniLogBreak {
            get {
                return ResourceManager.GetString("MiniLogBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files to analyze.
        /// </summary>
        internal static string NoFilesToAnalyze {
            get {
                return ResourceManager.GetString("NoFilesToAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleCop could not get the invisible form..
        /// </summary>
        internal static string NoInvisbleForm {
            get {
                return ResourceManager.GetString("NoInvisbleForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the attribute &apos;ProjectKind&apos; on the &apos;ProjectPathPropertyName&apos; node..
        /// </summary>
        internal static string NoProjectKindNodeFound {
            get {
                return ResourceManager.GetString("NoProjectKindNodeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the project property for the path to the property file. Possibly this is an error or a part missing in the parser xml file..
        /// </summary>
        internal static string NoProperProjectPathConfiguration {
            get {
                return ResourceManager.GetString("NoProperProjectPathConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the child node &apos;ProjectPathPropertyName&apos;..
        /// </summary>
        internal static string NoPropertyNameNodeFound {
            get {
                return ResourceManager.GetString("NoPropertyNameNodeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleCop {0} (build {1}) started.
        /// </summary>
        internal static string StyleCopStarted {
            get {
                return ResourceManager.GetString("StyleCopStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleCop.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get the path to the project..
        /// </summary>
        internal static string UnableToGetProjectPath {
            get {
                return ResourceManager.GetString("UnableToGetProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is unknown..
        /// </summary>
        internal static string UnknownFile {
            get {
                return ResourceManager.GetString("UnknownFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ========== Violation Count: {0} ==========.
        /// </summary>
        internal static string ViolationCount {
            get {
                return ResourceManager.GetString("ViolationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleCop.
        /// </summary>
        internal static string ViolationWindowCaption {
            get {
                return ResourceManager.GetString("ViolationWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string ViolationWindowCaptionWithViolationCount {
            get {
                return ResourceManager.GetString("ViolationWindowCaptionWithViolationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
