//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.StyleCop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.StyleCop.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The StyleCop settings file could not be saved to the path {0}: {1}.
        /// </summary>
        internal static string CouldNotSaveSettingsFile {
            get {
                return ResourceManager.GetString("CouldNotSaveSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write the violation mismatch detail log to {0}. The following exception occurred: {1}..
        /// </summary>
        internal static string CouldNotWriteDetailLog {
            get {
                return ResourceManager.GetString("CouldNotWriteDetailLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write the results file for test {0}..
        /// </summary>
        internal static string CouldNotWriteResultsFile {
            get {
                return ResourceManager.GetString("CouldNotWriteResultsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The violations produced by the test do not match the expected violations. .
        /// </summary>
        internal static string MismatchedViolations {
            get {
                return ResourceManager.GetString("MismatchedViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open the actual parser object model file at {0}.
        /// </summary>
        internal static string MissingActualObjectModelFile {
            get {
                return ResourceManager.GetString("MissingActualObjectModelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open the expected parser object model file at {0}.
        /// </summary>
        internal static string MissingExpectedObjectModelFile {
            get {
                return ResourceManager.GetString("MissingExpectedObjectModelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the test suite is missing..
        /// </summary>
        internal static string MissingOverallTestName {
            get {
                return ResourceManager.GetString("MissingOverallTestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open the StyleCop results file at {0}.
        /// </summary>
        internal static string MissingResultsFile {
            get {
                return ResourceManager.GetString("MissingResultsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test code file {0} does not exist..
        /// </summary>
        internal static string MissingTestCodeFile {
            get {
                return ResourceManager.GetString("MissingTestCodeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test does not contain any code files..
        /// </summary>
        internal static string MissingTestCodeFiles {
            get {
                return ResourceManager.GetString("MissingTestCodeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test description filefile {0} does not exist..
        /// </summary>
        internal static string MissingTestDescriptionFile {
            get {
                return ResourceManager.GetString("MissingTestDescriptionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test name is missing..
        /// </summary>
        internal static string MissingTestName {
            get {
                return ResourceManager.GetString("MissingTestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actual object model produced by the parser does not match the expected object model..
        /// </summary>
        internal static string ParserObjectModelMismatch {
            get {
                return ResourceManager.GetString("ParserObjectModelMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test description file {0} could not be loaded:{1}.
        /// </summary>
        internal static string TestDescriptionFileNotLoaded {
            get {
                return ResourceManager.GetString("TestDescriptionFileNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while running the test:{0}.
        /// </summary>
        internal static string TestException {
            get {
                return ResourceManager.GetString("TestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Unknown test).
        /// </summary>
        internal static string UnknownTest {
            get {
                return ResourceManager.GetString("UnknownTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Unknown test suite).
        /// </summary>
        internal static string UnknownTestSuite {
            get {
                return ResourceManager.GetString("UnknownTestSuite", resourceCulture);
            }
        }
    }
}
