//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleCop.VisualStudio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleCop.VisualStudio.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string ClassColumn {
            get {
                return ResourceManager.GetString("ClassColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string CommentColumn {
            get {
                return ResourceManager.GetString("CommentColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileColumn {
            get {
                return ResourceManager.GetString("FileColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string HighPriority {
            get {
                return ResourceManager.GetString("HighPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string LineColumn {
            get {
                return ResourceManager.GetString("LineColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string LowPriority {
            get {
                return ResourceManager.GetString("LowPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string MediumPriority {
            get {
                return ResourceManager.GetString("MediumPriority", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap priority {
            get {
                object obj = ResourceManager.GetObject("priority", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string PriorityColumn {
            get {
                return ResourceManager.GetString("PriorityColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority Number.
        /// </summary>
        internal static string PriorityNumberColumn {
            get {
                return ResourceManager.GetString("PriorityNumberColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string ProjectColumn {
            get {
                return ResourceManager.GetString("ProjectColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement.
        /// </summary>
        internal static string ReplacementColumn {
            get {
                return ResourceManager.GetString("ReplacementColumn", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap StyleCop {
            get {
                object obj = ResourceManager.GetObject("StyleCop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        internal static string TermColumn {
            get {
                return ResourceManager.GetString("TermColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleCop.
        /// </summary>
        internal static string ViolationsWindowCaption {
            get {
                return ResourceManager.GetString("ViolationsWindowCaption", resourceCulture);
            }
        }
    }
}
