// <auto-generated/>

// Everything in the wrong order but it doesn't matter since the file is generated.
private class Class1 { }
protected class Class2 { }
internal protected class Class3 { }
internal class Class4 { }
public class Class5 { }

private struct Struct1 { }
protected struct Struct2 { }
internal protected struct Struct3 { }
internal struct Struct4 { }
public struct Struct5 { }

private interface Interface1 { }
protected interface Interface2 { }
internal protected interface Interface3 { }
internal interface Interface4 { }
public interface Interface5 { }

private enum Enum1 { }
protected enum Enum2 { }
internal protected enum Enum3 { }
internal enum Enum4 { }
public enum Enum5 { }

private delegate void Delegate1();
protected delegate void Delegate2();
internal protected delegate void Delegate3();
internal delegate void Delegate4();
public delegate void Delegate5();

namespace ElementOrderGlobalGeneratedCode1
{
    private class Class6 { }
    protected class Class7 { }
    internal protected class Class8 { }
    internal class Class9 { }
    public class Class10 { }

    private struct Struct6 { }
    protected struct Struct7 { }
    internal protected struct Struct8 { }
    internal struct Struct9 { }
    public struct Struct10 { }

    private interface Interface6 { }
    protected interface Interface7 { }
    internal protected interface Interface8 { }
    internal interface Interface9 { }
    public interface Interface10 { }

    private enum Enum6 { }
    protected enum Enum7 { }
    internal protected enum Enum8 { }
    internal enum Enum9 { }
    public enum Enum10 { }

    private delegate void Delegate6();
    protected delegate void Delegate7();
    internal protected delegate void Delegate8();
    internal delegate void Delegate9();
    public delegate void Delegate10();
}

namespace ElementOrderGlobalGeneratedCode2
{
    public class NamespaceClass1
    {
        private class SubClass1 { }
        protected class SubClass2 { }
        internal protected class SubClass3 { }
        internal class SubClass4 { }
        public class SubClass5 { }

        private struct Struct11 { }
        protected struct Struct12 { }
        internal protected struct Struct13 { }
        internal struct Struct14 { }
        public struct Struct15 { }

        private void Method1() { }
        protected void Method2() { }
        internal protected void Method3() { }
        internal void Method4() { }
        public void Method5() { }
        private static void Method6() { }
        protected static void Method7() { }
        internal static protected void Method8() { }
        internal static void Method9() { }
        public static void Method10() { }

        private bool this[int x] { get { return true; } }
        protected bool this[short x] { get { return true; } }
        internal protected bool this[long x] { get { return true; } }
        internal bool this[float x] { get { return true; } }
        public bool this[double x] { get { return true; } }

        private bool Property1 { get { return true; } }
        protected bool Property2 { get { return true; } }
        internal protected bool Property3 { get { return true; } }
        internal bool Property4 { get { return true; } }
        public bool Property5 { get { return true; } }
        private static bool Property6 { get { return true; } }
        protected static bool Property7 { get { return true; } }
        internal static protected bool Property8 { get { return true; } }
        internal static bool Property9 { get { return true; } }
        public static bool Property10 { get { return true; } }

        private interface Interface11 { }
        protected interface Interface12 { }
        internal protected interface Interface13 { }
        internal interface Interface14 { }
        public interface Interface15 { }

        private enum Enum11 { }
        protected enum Enum12 { }
        internal protected enum Enum13 { }
        internal enum Enum14 { }
        public enum Enum15 { }

        private event EventHandler Event1 { }
        protected event EventHandler Event2 { }
        internal protected event EventHandler Event3 { }
        internal event EventHandler Event4 { }
        public event EventHandler Event5 { }

        private delegate void Delegate11();
        protected delegate void Delegate12();
        internal protected delegate void Delegate13();
        internal delegate void Delegate14();
        public delegate void Delegate15();

        ~NamespaceClass1()
        {
        }

        private NamespaceClass1(int x) { }
        protected NamespaceClass1(short x) { }
        internal protected NamespaceClass1(long x) { }
        internal NamespaceClass1(float x) { }
        public NamespaceClass1(double x) { }
        static NamespaceClass1(string x) { }

        private int field1;
        protected int field2;
        internal protected int field3;
        internal int field4;
        public int field5;
        private const int field6 = 0;
        protected const int field7 = 0;
        internal protected const int field8 = 0;
        internal const int field9 = 0;
        public const int field10 = 0;
        private readonly int field11;
        protected readonly int field12;
        internal protected readonly int field13;
        internal readonly int field14;
        public readonly int field15;
        private static int field16;
        protected static int field17;
        internal protected static int field18;
        internal static int field19;
        public static int field20;
    }
}




