//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleCop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleCop.LogStrings", typeof(LogStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to load add-in initialization Xml from path {0}.
        /// </summary>
        internal static string AttemptingToLoadAddInInitializationXmlFromPath {
            get {
                return ResourceManager.GetString("AttemptingToLoadAddInInitializationXmlFromPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find add-in initialization Xml.
        /// </summary>
        internal static string CouldNotFildAddInInitializationXml {
            get {
                return ResourceManager.GetString("CouldNotFildAddInInitializationXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating an instance of type {0}.
        /// </summary>
        internal static string CreatingAnInstanceOfType {
            get {
                return ResourceManager.GetString("CreatingAnInstanceOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered SourceAnalyzer type {0}.
        /// </summary>
        internal static string DiscoveredSourceAnalyzerType {
            get {
                return ResourceManager.GetString("DiscoveredSourceAnalyzerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered SourceParser type {0}.
        /// </summary>
        internal static string DiscoveredSourceParserType {
            get {
                return ResourceManager.GetString("DiscoveredSourceParserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load add-in initialization Xml.
        /// </summary>
        internal static string FailedToLoadAddInInitializationXml {
            get {
                return ResourceManager.GetString("FailedToLoadAddInInitializationXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading add-ins from path {0}.
        /// </summary>
        internal static string LoadAddInsFromPath {
            get {
                return ResourceManager.GetString("LoadAddInsFromPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading assembly {0}.
        /// </summary>
        internal static string LoadingAssembly {
            get {
                return ResourceManager.GetString("LoadingAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} does not contain the StyleCopAddInAttribute.
        /// </summary>
        internal static string TheTypeDoesNotContainTheStyleCopAddInAttribute {
            get {
                return ResourceManager.GetString("TheTypeDoesNotContainTheStyleCopAddInAttribute", resourceCulture);
            }
        }
    }
}
