/*----------------------------------------------------------------------
Copyright (c) Microsoft Corporation.  All rights reserved.

@doc
@module IVsProjectMRU.idl |

This interface is called by source control providers to register additional
information on the Project MRU list about a project that was opened from
source control or added to source control.

@owner Source Control Integration Team
----------------------------------------------------------------------*/

#ifndef INTEROPLIB
    // Includes -------------------------------------------------------------------
    import "oaidl.idl";
#endif

// Types and Constants --------------------------------------------------------
// None.

// Globals --------------------------------------------------------------------
// None.

// Interfaces -----------------------------------------------------------------

#ifndef PROXYSTUB_BUILD

//---------------------------------------------------------------------------
// SVsProjectMRU
// The service type implementing IVsProjectMRU
//---------------------------------------------------------------------------
/*----------------------------------------------------------------------------- 
Name: SVsProjectMRU

@interface SVsProjectMRU  | 

@owner Source Control Integration Team

@base public | IUnknown 
-----------------------------------------------------------------------------*/
[
    uuid(D8982A22-9CE1-45ED-963C-815854B1CFA2),
    version(1.0),
    pointer_default(unique)
]
interface SVsProjectMRU : IUnknown
{
};

cpp_quote("#define SID_SVsProjectMRU IID_SVsProjectMRU")

#endif // PROXYSTUB_BUILD

/*----------------------------------------------------------------------------- 
Name: IVsProjectMRU

@interface IVsProjectMRU  | 

@owner Source Control Integration Team

@base public | IUnknown 
-----------------------------------------------------------------------------*/

[uuid (D60EDEEA-3629-42CC-BAAF-9AC52E63EEAF)]
interface IVsProjectMRU : IUnknown
{
    HRESULT RegisterProjectMRU
        (
        [in] LPCOLESTR szLocalPath,          // Local path to the project/solution
        [in] LPCOLESTR szProviderString,     // Provider specific string, that ideally can be used to open the solution from source control.
        [in] LPCOLESTR szDisplayText,        // Additional text that will be displayed in the Start Page MRU list for the project/solution.
        [in] LPCOLESTR szToolTipDisplayText, // Additional line of text that will be displayed in the Start Page MRU tooltip for the project/solution
        [in] REFGUID   providerId            // Id of the source control provider that is calling the method.
        );
};
 
